# version: 0.2

# phases:
#   pre_build:
#     commands:
#       - npm install
#   build:
#     commands:
#       - npm run build

# artifacts:
#   files:
#     - '**/*'
#   discard-paths: no
#   base-directory: ./

# --------------------------------------------------------------------------------------------------

version: 0.2

# Build the code
phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - echo "----- Node Version--------------------------------------"
      - node --version
      # - npm i @angular/cli@13.3.9
      - npm install -g @angular/cli@latest
      # - npm install -g @angular/cli@8.3.29

      - ng version
      - npm install -g @nestjs/cli
      - cd backend
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - nest build
      - cd ../frontend
      - npm install
      - ls
      - echo "--------- build angular app --------------------"
      - ng build
      - mv ./dist/frontend ./../backend/dist/frontend
      # - cd ..
      # - mv ./dist/* .
  post_build:
    commands:
      - echo Build completed on `date`
      - cd ../backend
      - cp ./package.json ./../
      - cd ..
      - echo "Build finished "
      - ls
      - echo " ------------------------------------------------------------------------------------ "
      - cd dist
      - ls
      - echo " ------------------------------------------------------------------------------------ "

# Include only the files required for your application to run.
artifacts:
  files:
    - Procfile
    - dist/*
    - package.json
# -----------------------------------------------------------------------------------------------------

# # Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
# version: 0.2

# phases:
#   install:
#     runtime-versions:
#       nodejs: 10
#   pre_build:
#     commands:
#       - echo Installing source NPM dependencies...
#       - npm install
#   build:
#     commands:
#       - echo Build started on `date`
#       # - echo Compiling the Node.js code
#       # - mocha test.js
#   post_build:
#     commands:
#       - echo Build completed on `date`
# # Include only the files required for your application to run.
# # Do not use recursively include artifacts from node_modules directory as it will include unnecessary packages
# # used only for building and testing.
# # ExpressJS apps will need other artifact directories included (bin/*, public/*, routes/*, views/* etc).
# artifacts:
#   files:
#     - app.js
#     - package.json
#     - node_modules/*
